# Generated by Django 4.1.6 on 2023-02-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='', max_length=100)),
                ('screen', models.CharField(default='', max_length=100)),
                ('cpu', models.CharField(default='', max_length=100)),
                ('vga', models.CharField(default='', max_length=100)),
                ('ram', models.CharField(default='', max_length=100)),
                ('harddisk', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
