# Generated by Django 4.1.6 on 2023-02-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App11', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default='', max_length=6, primary_key=True, serialize=False),
        ),
    ]
